import re

# f = open("24_9753.txt").read()
#
# f = f.split("Y")
# maxx = "Y"
# for i in range(len(f)):
#     x = f[i:i + 151]
#
#     st = "Y".join(x)
#
#     if len(maxx) < len(st):
#         maxx = st
#
#
# print(maxx)
# print(len(maxx))

f = open("24_9753.txt").read()
pat = r"(?=[TUVWXZ]*(?:Y[TUVWXZ]*){150})"

c = r"[TUVWXZ]"
# pat= rf"{c}*(?:Y{c}*)\{150}"


res = re.findall(pat, f)

print(max(res, key=len))
print(max(res, key=len).count("Y"))
print(len(max(res, key=len)))


# YVYYYYYYUXVWUYYYYVWYXXYYYVYYYTZYYYUYYYXYYYZWVUYYYYUYYYYTYYVYXYXWYYYVYYYYVWYVYYYZXZTYTUXYWUYVWTYYYWVYYYYYYYYYYYYYYYUYZYYYYYVVVZXYYYYYTYYYYWYYYYZYYYWYYYZYYYUYWVYZYXXXWUYYWYTYYUVYYVXYYYZYUVYYTYYZYYYTYTYWYYYYYYYYYYVYYYWZYYYYYZYYXZYYWYYWYYZYY
# YTXTYYWYWYYUXXXYUYYTYTXYYWVYWYYYUVYTWYYUYTYYYZYYYYYYZTYYYYYVYYYWXZWUYYYYUYVYYYVYYYYYYYYYYYTXYTYYUZWVTYYYYYYWXYWYYYVTUYYYYYTYWYYWYYYWYVYYWYZYYYYWZYWYYXXXYWYYTYYXYUYYWYYYYYYVYYYUUTWYYYZTUYYYWYZYYTYYYXYZYYWYYYZYTYYUYYUTYZYYVYYYYTVYWYYYYYYYYXVYYWYT